SLING-11140 Update bundles to the latest releases
Revert the feature launcher update since it immediately errors out:

Error: Unable to initialize main class org.apache.sling.feature.launcher.impl.Main
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException